projects:
  TAGE API:
    schemaPath: src/graphql/schema.json
    includes:
      - '*.js'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: a6l2llmvdnbvjkamxm54yuy7nm
        maxDepth: 2
extensions:
  amplify:
    version: 3
